# Functions II -- solutions

## EOSC 211

**Week 8 Day 2**

**Learning Objectives:**  
1. Implement functions in your code
2. Understand the difference between a *fruitful* function (one that returns a variable) and void functions (one that performs an action but does not return anything

## Question 1

**We have two input arrays, `x` which is distance and `tpro` which is elevation in kilometers (say, along a survey line). Both have shape (100,). Use a *loop* and an *if statement* to write out a new variable `tlow` that contains only the values in `tpro` when the elevation is less than -1.8km.**

In [1]:
import numpy as np

x = np.linspace(0, 1000, 100)  # km along the survey line
tpro = -1.5 + 0.5 * np.sin(x) # pretend topo

# your code here

In [2]:
# andrew's soln
tlow = np.array([])
for i in tpro:
    if i < 0.5:
        tlow = np.append(tlow,i)

print(tlow)

[-1.5        -1.81292939 -1.01186996 -1.94849139 -1.28854053 -1.38135848
 -1.89652514 -1.00011274 -1.8832354  -1.40208879 -1.26949364 -1.95747182
 -1.01690852 -1.79608944 -1.52122962 -1.17079506 -1.99228822 -1.06129795
 -1.69203118 -1.63915784 -1.09090029 -1.99898567 -1.13074554 -1.57700432
 -1.74913752 -1.03437285 -1.97718161 -1.22128454 -1.45757905 -1.84488674
 -1.0044415  -1.92812148 -1.32774345 -1.34057683 -1.92093642 -1.0028159
 -1.85460753 -1.44404146 -1.23268067 -1.97294268 -1.0295889  -1.76083879
 -1.56353576 -1.1400535  -1.99793499 -1.08323125 -1.65217124 -1.67940097
 -1.06798607 -1.99448581 -1.16067897 -1.53481183 -1.785019   -1.02059478
 -1.96279215 -1.25750832 -1.41546401 -1.87435706 -1.00058659 -1.90466433
 -1.36818853 -1.3009448  -1.94231227 -1.00910433 -1.82342253 -1.48639766
 -1.19779539 -1.98500309 -1.04566148 -1.7237072  -1.60538374 -1.11190757
 -1.99999108 -1.10816994 -1.61121396 -1.71835042 -1.04818715 -1.98642015
 -1.19305929 -1.49236831 -1.81884517 -1.01027378 -1.

In [3]:
# catherine's solution   
# same as Andrew's but i used "t" not "i" to remind myself i am looping over the values in tpro not their indices

import numpy as np

x = np.linspace(0, 1000, 100)  # km along the survey line
tpro = -1.5 + 0.5 * np.sin(x) # pretend topo

tlow=np.array([])   # Defining tlow as numpy array for consistency with type(x), type(tpro).  
for t in tpro:
    if (t<-1.8):
        tlow=np.append(tlow,t)
print(tlow)

[-1.81292939 -1.94849139 -1.89652514 -1.8832354  -1.95747182 -1.99228822
 -1.99898567 -1.97718161 -1.84488674 -1.92812148 -1.92093642 -1.85460753
 -1.97294268 -1.99793499 -1.99448581 -1.96279215 -1.87435706 -1.90466433
 -1.94231227 -1.82342253 -1.98500309 -1.99999108 -1.98642015 -1.81884517
 -1.94506543 -1.90112784 -1.87828908 -1.96049853 -1.99356607]


## Question 2

**Turn the code snippet above into a function that returns an array `tlow` that is exactly the same as Q1, but that takes as input (1) `in_data` and (2) a variable called `cutoff` that contains an arbitrary cut-off for the elevation  (ie, I might want to select elevations below -2km or -1.8 km or -1.5km, so make this a variable).**

**Finally, call your function with tpro as the input data and a cutoff of -1.8 km**

In [4]:
# your code here

In [5]:
# catherine's soln
def select_elev(in_data, cutoff):
    """
    selects elements of a 1D np array in_data which are below the value cutoff.
    returns elements of in_data which are below cutoff
    """
    tlow = np.array([])
    for t in tpro:
        if t < cutoff:
            tlow = np.append(tlow, t)
    return tlow

select_elev(tpro, -1.8)

array([-1.81292939, -1.94849139, -1.89652514, -1.8832354 , -1.95747182,
       -1.99228822, -1.99898567, -1.97718161, -1.84488674, -1.92812148,
       -1.92093642, -1.85460753, -1.97294268, -1.99793499, -1.99448581,
       -1.96279215, -1.87435706, -1.90466433, -1.94231227, -1.82342253,
       -1.98500309, -1.99999108, -1.98642015, -1.81884517, -1.94506543,
       -1.90112784, -1.87828908, -1.96049853, -1.99356607])

## Question 3

**Modify your function to return a *tuple* containing the elevations below `cutoff`, and the *indexes* of where those elements are found; ie `(tlow, tlow_ind)`.**

In [6]:
# your code here

In [7]:
# andrew's soln; catherine's basically the same
def select_elev2(in_data, cutoff):
    """
    selects elements of a 1D np array in_data which are below the value cutoff.
    returns elements of in_data which are below cutoff
    """
    tlow = np.array([])
    tlow_ind = np.array([])
    for i in range(len(in_data)):    # note that i is now an index into the in_data array
        if in_data[i] < cutoff: 
            tlow_ind = np.append(tlow_ind, i)
            tlow = np.append(tlow, in_data[i])
    return tlow, tlow_ind

low, ind = select_elev2(tpro, -1.5)
low, ind

(array([-1.81292939, -1.94849139, -1.89652514, -1.8832354 , -1.95747182,
        -1.79608944, -1.52122962, -1.99228822, -1.69203118, -1.63915784,
        -1.99898567, -1.57700432, -1.74913752, -1.97718161, -1.84488674,
        -1.92812148, -1.92093642, -1.85460753, -1.97294268, -1.76083879,
        -1.56353576, -1.99793499, -1.65217124, -1.67940097, -1.99448581,
        -1.53481183, -1.785019  , -1.96279215, -1.87435706, -1.90466433,
        -1.94231227, -1.82342253, -1.98500309, -1.7237072 , -1.60538374,
        -1.99999108, -1.61121396, -1.71835042, -1.98642015, -1.81884517,
        -1.94506543, -1.90112784, -1.87828908, -1.96049853, -1.78990528,
        -1.52885195, -1.99356607, -1.68496242, -1.64647178]),
 array([ 1.,  3.,  6.,  8., 11., 13., 14., 16., 18., 19., 21., 23., 24.,
        26., 29., 31., 34., 36., 39., 41., 42., 44., 46., 47., 49., 51.,
        52., 54., 57., 59., 62., 64., 67., 69., 70., 72., 74., 75., 77.,
        80., 82., 85., 87., 90., 92., 93., 95., 97., 98.]))

## Question 4

**Finally, I need not have used a loop and an “if” statement in the function.  How would I rewrite the body of the function in Exercise 2 to use logical indexing?  Note that the function call and function definition line don’t need to be changed.**

In [8]:
# your code here

In [9]:
# andrew's soln
def select_elev3(in_data, cutoff):
    """
    selects elements of a 1D np array in_data which are below the value cutoff.
    returns elements of in_data which are below cutoff
    """
    return in_data[in_data < cutoff]
    
select_elev3(tpro, -1.8)

array([-1.81292939, -1.94849139, -1.89652514, -1.8832354 , -1.95747182,
       -1.99228822, -1.99898567, -1.97718161, -1.84488674, -1.92812148,
       -1.92093642, -1.85460753, -1.97294268, -1.99793499, -1.99448581,
       -1.96279215, -1.87435706, -1.90466433, -1.94231227, -1.82342253,
       -1.98500309, -1.99999108, -1.98642015, -1.81884517, -1.94506543,
       -1.90112784, -1.87828908, -1.96049853, -1.99356607])