# Notes for Thursday Oct. 7

## Week 5 lab

1.) Watch your brackets:

* `cosine(the_lat_radians)`  -- function evaluation
* `topo[i,j+1]`  -- indexing

2.) Simplify complex formulas by evaluating pieces separately

     numerator=(a + b)**3. - np.exp(c)  
     denom = cos(5z) - np.log(y)`  
     slope = np.arctan(umerator/denom)  

3.)  When in doubt about how row/colum relate to lat/lon on an image, draw a dot
     on your map

## Objects, instances, and types

* [A glossary](https://eli.thegreenplace.net/2012/03/30/python-objects-types-classes-and-instances-a-glossary)

* A type or class:  np.array or NoneType

* An instance or object:  np.array([5,6,7]) or None

## Untangling spaghetti code

1.) Comment your code to make your intent clear  
2.) For choosing one among many, use the `in` keyword

### Example: Find an item in a list

In [1]:
guestlist = ['tom','betty','ulma']
guest = 'ulma'
if guest in guestlist:
    print(f"Welcome {guest}!")

Welcome ulma!


3.) Use dictionaries to hold functions and slices by keyword

### Example:  return a slice from a dictionary

Suppose that if our map projection is mercator, then our study region (Vancouver Island) is
located between row 10 and row 20 and column 100 and column 107 on a series of satellite images.
If our map projection is Lambert Azimuthal, then there's a different set of corners for the region.
How would we find the right slice without an if/else block?

Answer: store the slices in a dictionary and look them up by dictionary key

In [2]:
# make a fake image

import numpy as np
numcols = 200
numrows = 100
fake_image = np.arange(0,numcols*numrows).reshape([numrows,numcols])
print(fake_image[0:10,0:5])

[[   0    1    2    3    4]
 [ 200  201  202  203  204]
 [ 400  401  402  403  404]
 [ 600  601  602  603  604]
 [ 800  801  802  803  804]
 [1000 1001 1002 1003 1004]
 [1200 1201 1202 1203 1204]
 [1400 1401 1402 1403 1404]
 [1600 1601 1602 1603 1604]
 [1800 1801 1802 1803 1804]]


In [3]:
# make a dictionary that has 'mercator' as its first key, and holds another dictionary with
# 'rows' and 'columns' keys for that map projection

row_slice = slice(10,20)  # 10:20
column_slice = slice(100,107)  # 100:107
corner_dict = dict()
corner_dict['mercator'] = {'rows': row_slice,'columns':column_slice}
## now use these slices on the fake_image

projection='mercator'
island_rows = corner_dict[projection]['rows']
island_columns = corner_dict[projection]['columns']
island_image = fake_image[island_rows,island_columns]
print(island_image)

[[2100 2101 2102 2103 2104 2105 2106]
 [2300 2301 2302 2303 2304 2305 2306]
 [2500 2501 2502 2503 2504 2505 2506]
 [2700 2701 2702 2703 2704 2705 2706]
 [2900 2901 2902 2903 2904 2905 2906]
 [3100 3101 3102 3103 3104 3105 3106]
 [3300 3301 3302 3303 3304 3305 3306]
 [3500 3501 3502 3503 3504 3505 3506]
 [3700 3701 3702 3703 3704 3705 3706]
 [3900 3901 3902 3903 3904 3905 3906]]
